### PR TITLE
Sachin liyanage quick sort c# - #62

### PR DESCRIPTION
**Pull request by Sachin-Liyanage**
## Have you read the Contribution Guidelines?

(Write your answer here.)

## Description

(Write your answer here.)

## Checklist
- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the README.md and link to my code.

## Related Issues (Mention Issue no. like #xxx)

Fixes Issue
<br/>
(Write your answer above.)

### CODE REVIEW

**Comment by manan025** [comment]
Please read CONTRIBUTING.md. You haven't mentioned the issue number in the PR.

**Comment by manan025** [comment]
#62

**Review by manan025 — CHANGES_REQUESTED** [review]
Add sample I/O, I/O format, time and space complexity.

**Comment by Sachin-Liyanage** [comment]
@manan025, I'll do them 👍

**Comment by manan025** [comment]
Oh I see that's in the title. Sorry I didn't see that.

**Pull request closed without merging**
