### PR TITLE
Palindrome Check added

### PR DESCRIPTION
**Pull request by sourabmaity**
## Have you read the Contribution Guidelines?

Yes

## Description

palindrome check program in go

## Checklist
- [Y ] I've read the contribution guidelines.
- [ Y] I've checked the issue list before deciding what to submit.
- [ Y] I've edited the README.md and link to my code.

## Related Issues (Mention Issue no. like #14 )

Fixes Issue
yse
(Write your answer above.)

### CODE REVIEW

**Review by manan025 — CHANGES_REQUESTED** [review]
Add Sample IO, Time and space complexity please.

**Comment by SOURAB-BAPPA** [comment]
complexity and example added

**Review by manan025 — APPROVED** [review]
Great

**Comment by sourabmaity** [comment]
hacktoberfest is not accepting your repo contribution

**Comment by manan025** [comment]
@SOURAB-BAPPA Yes, according to their rules, DSA repositories won't be considered.
I'm sorry.

**Pull request merged**
