### PR TITLE
Dijkstra Algorithm in C++

### PR DESCRIPTION
**Pull request by vedant-jain03**
## Have you read the Contribution Guidelines?

Yes

## Description

Add Dijkstra Algorithm to find single source shortest path in weighted graph.

## Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.

## Related Issues (Mention Issue no. like #xxx)

Fixes Issue
<br/>
#78

### CODE REVIEW

**Review by manan025 — CHANGES_REQUESTED** [review]
Please add Sample IO, Time and space complexity

**Comment by vedant-jain03** [comment]
I have try manually input and I have commented it below with time and space complexity. Is it okay ?

**Comment by manan025** [comment]
Sure

**Review by manan025 — APPROVED** [review]
Approved

**Comment by vedant-jain03** [comment]
@manan025 is anything else I had to do to get labelled for hacktoberfest-accepeted on pr

**Pull request merged**
