### PR TITLE
Added merge sort Javascript (Issue #60)

### PR DESCRIPTION
**Pull request by Onkar627**
## Have you read the Contribution Guidelines?

(Write your answer here.)

## Description

(Write your answer here.)

## Checklist
- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the README.md and link to my code.

## Related Issues (Mention Issue no. like #xxx)

Fixes Issue
<br/>
(Write your answer above.)

### CODE REVIEW

**Comment by manan025** [comment]
Please fill the PR from the next time.

**Comment by Onkar627** [comment]
Okay :)

**Comment by Onkar627** [comment]
Could you please add the label 😃

**Comment by manan025** [comment]
@Onkar627 I'll add it in bulk i.e. I'll add once I am done with reviewing PRs.

**Pull request merged**
