### PR TITLE
Vertical tree traversal

### PR DESCRIPTION
**Pull request by ishika22**
## Have you read the Contribution Guidelines?

yes
## Description

Vertical tree traversal
## Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.

## Related Issues (Mention Issue no. like #xxx)

Fixes Issue
<br/>
(Write your answer above.)

### CODE REVIEW

**Comment by ishika22** [comment]
@manan025 please review. Added sample test cases alongwith solution

**Comment by ishika22** [comment]
Solves #108

**Comment by ishika22** [comment]
@manan025 can you please accept this PR. let me know if any changes are to be done

**Comment by manan025** [comment]
Sorry for the delay. (It won't impact your Hacktoberfest progress though).

**Review by manan025 — APPROVED** [review]
👏

**Comment by ishika22** [comment]
No problem @manan025 . Thanks for accepting the PR.

**Pull request merged**
