### PR TITLE
Added Kadane's Algorithm in Python and Updated Readme.md

### PR DESCRIPTION
**Pull request by anushkarthik05**
## Have you read the Contribution Guidelines?

Yes

## Description

Added Kadane's Algorithm to find largest sum contiguous subarray in Python and updated Readme.md

## Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.

## Related Issues (Mention Issue no. like #xxx)

Fixes Issue
<br/>
#68
(Write your answer above.)

### CODE REVIEW

**Comment by anushkarthik05** [comment]
@manan025. I have resolved some conflicts and now it is ready for merge.

**Review by manan025 — APPROVED** [review]

**Comment by anushkarthik05** [comment]
Can you add the label if accepted. @manan025

**Comment by manan025** [comment]
@anushkarthik05 I'll add it in bulk i.e. I'll open PR lists and will use shortcuts to add label in them one by one in flow. 😅
(Might sound kiddish but I feel satisfactory when I do that)

**Comment by manan025** [comment]
Don't worry, that won't impact your hacktoberfest progress.

**Comment by anushkarthik05** [comment]
> Don't worry, that won't impact your hacktoberfest progress.

Cool Thanks!!

**Pull request merged**
