### PR TITLE
Added Quick short in c and update Readme file

### PR DESCRIPTION
**Pull request by JatinKumarMahaldar**
That's my first time to work on github and open source  if there is anything wrong please let me know so that i can improve myself .

### CODE REVIEW

**Comment by JatinKumarMahaldar** [comment]
can't understand what conflict is there please can you make  me understand it will be helpfull .

**Review by manan025 — APPROVED** [review]
Amazing!

**Comment by manan025** [comment]
> 
> 
> can't understand what conflict is there please can you make me understand it will be helpfull .

You might have written something on a line and there was something else written on the same line in my repo. (Happens but don't worry, I'll resolve it)

Also mention the Issue number using `#` so that it is easy to see if you were assigned the work.

**Comment by JatinKumarMahaldar** [comment]
Thank you @manan025

**Comment by JatinKumarMahaldar** [comment]
@manan025 can u please tell what was that README.md conflict so that i can correct myself next time .

**Comment by manan025** [comment]
On the line where you entered location of Quick sort program, someone else had written location of Bubble sort program. But that code wasn't updated in your forked repo and hence you didn't know about it. When you made PR, it matched your code with my code and found that there are 2 entries for the same line so it was asking me to select one/ both of them. I opened "Resolve merge"... and removed extra lines and separated both the entries to different lines.

**Pull request merged**
