### PR TITLE
Added DFS and BFS on a 2d grid

### PR DESCRIPTION
**Pull request by Mudit018**
## Have you read the Contribution Guidelines?

YES

## Description

Added DFS and BFS on a 2d grid

## Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.

## Related Issues (Mention Issue no. like #xxx)

Fixes Issue #155 
<br/>

### CODE REVIEW

**Comment by Mudit018** [comment]
@manan025 I have resolved the conflict twice, can you merge this PR.

**Comment by Mudit018** [comment]
@manan025 Could you please merge my PR, I've fixed the merge conflicts.

**Comment by Mudit018** [comment]
@manan025 Could you tell whether these PRs will be considered for Hacktoberfest or not because it is not showing there that we have completed our work. It is giving us a period of 14 days

**Comment by manan025** [comment]
Yeah, it will be counted after 14 days.
14 days has been given for the maintainer to verify all the details.

**Comment by Mudit018** [comment]
@manan025 Okay thanks man

**Pull request merged**
