### PR TITLE
Added Fibonacci series in c and updated README.md

### PR DESCRIPTION
**Pull request by JatinKumarMahaldar**
## Have you read the Contribution Guidelines?

yes

## Description

(Write your answer here.)

## Checklist
- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the README.md and link to my code.

## Related Issues (Mention Issue no. like #xxx)

Fixes Issue

Added Fibonacci series in c and updated README.md #

### CODE REVIEW

**Comment by JatinKumarMahaldar** [comment]
@manan025 i have committed one more file i.e (added pascal triangle and updated README.md) how can i make a separate pull request for this , can you please help me with this .

**Review by manan025 — APPROVED** [review]

**Comment by manan025** [comment]
Use branches inside a repo

**Comment by JatinKumarMahaldar** [comment]
@manan025 you mean to create different branches for each different issues right.

**Comment by manan025** [comment]
Yes

**Pull request merged**
